# Generated by Django 3.0 on 2019-12-14 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant_basics',
            name='family',
        ),
    ]
