# Generated by Django 3.0 on 2019-12-31 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0005_auto_20191214_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant_basics',
            name='common_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='plant_basics',
            name='symbol',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
