# Generated by Django 3.0 on 2019-12-31 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0006_auto_20191231_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant_basics',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
