# Generated by Django 3.0 on 2019-12-31 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0007_auto_20191231_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='family_description',
            field=models.TextField(null=True),
        ),
    ]
