# Generated by Django 3.0 on 2020-11-03 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0008_auto_20191231_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant_basics',
            name='frequency',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PlantImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('plant_basics', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='plants.plant_basics')),
            ],
        ),
    ]
