# Generated by Django 3.0 on 2020-11-03 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0009_auto_20201103_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantimages',
            name='additional_image_description',
            field=models.TextField(null=True),
        ),
    ]
